### PR TITLE
Add wrap for check 0.14.0

### PR DESCRIPTION
**Pull request by JPTIZ**
This PR should solve #2.

From https://mesonbuild.com/Wrap-review-guidelines.html:

```
- [x] project() has version string
- [x] project() has license string
- [x] if new project, master has tagged commit as only commit
- [x] if new branch, it is branched from master
- [x] contains a readme.txt
- [x] contains an upstream.wrap file
- [x] download link points to authoritative upstream location
- [x] wrap repository contains only build system files
- [x] merge request is pointed to correct target branch (not master)
- [x] wrap works
- [x] repo does not have useless top level directory (i.e. libfoobar-1.0.0)
```

## Current issues

~I've marked two items with `?` because I don't know how to do/confirm it's been done right.~
- ~About the new project, "tagget commit as only commit" means some special tagging? In that case, would it be the `commit_zero` tag?~ Solved
- ~About to the correct branch, `0.14.0` is currently not a branch in `mesonbuild/check`. As a placeholder I've set `0.10.0` as target.~ Solved

~Also, I'm not quite used to license headings in source-code, so I've let config.h.meson almost as it was from cmake/config.h.in.~ Solved by explicitly stating it was a copy from another file + removing license from top of `config.h.meson`.

~After solving these issues I should then set this as a ready-for-review PR.~ Issues solved, ready for review.

### CODE REVIEW

**Comment by legeana** [comment]
- [?] merge request is pointed to correct target branch (not master) -- fixed.
- [?] if new project, master has tagged commit as only commit -- not needed.

It seems you used Jussi's code. He gave a blank license for any contributions to wraps he made to be distributed under the MIT license. Where the license comes from for the files included in the original PR I unfortunately can't advise as I am not a lawyer. It is on the author of the PR to ensure that the files included in the PR can be redistributed legally. If you think changing the LICENSE.build may be beneficial please feel free to do so.

**Comment by JPTIZ** [comment]
>     * [?] merge request is pointed to correct target branch (not master) -- fixed.
> 
>     * [?] if new project, master has tagged commit as only commit -- not needed.

Thanks! :)

> It seems you used Jussi's code. He gave a blank license for any contributions to wraps he made to be distributed under the MIT license.

Oh, I see.

> Where the license comes from for the files included in the original PR I unfortunately can't advise as I am not a lawyer. It is on the author of the PR to ensure that the files included in the PR can be redistributed legally. If you think changing the LICENSE.build may be beneficial please feel free to do so.

In that case, I commited now a workaround by explicitly stating that `config.h.meson` is a copy of `config.h.in` with necessary adaptations for meson. So no more need to worry about it :) Gonna open for review.

**Comment by legeana** [comment]
Hi, there are 2 issues with the PR:
1. It would be nice to put a `LICENSE.build`, you can take a look on the master branch or make your own. This is the license that covers build files you contribute. Jussi's code is licensed under MIT so if you would like to reuse MIT it's perfectly fine. You can just use the file from the master branch verbatim.
2. The code doesn't build. The log is below.

```
$ mesonwrap review check --pull-request=3 --allow-no-license --allow-other-files
Inspecting project check, branch 0.14.0.
Repo name valid: ☑
Branch name valid: ☑
Target branch is not master: ☑
Has readme.txt: ☑
Has LICENSE.build: ☒
Has upstream.wrap: ☑
Non-buildsystem files found:
  internal/config.h.meson
Repo contains only buildsystem files: ☒
upstream.wrap has directory: ☑
upstream.wrap directory has no path separators: ☑
upstream.wrap has source_url: ☑
upstream.wrap has source_filename: ☑
upstream.wrap source_filename has no path separators: ☑
upstream.wrap has source_hash: ☑
upstream.wrap has source_url with version substring: ☑
Download URL works: ☑
Hash matches: ☑
upstream.wrap directory 'check-0.14.0' exists: ☑
Patch merges with source: ☑
The Meson build system
Version: 0.54.1
Source dir: /tmp/tmpmwdxrkof/src/check-0.14.0
Build dir: /tmp/tmpmwdxrkof/bin
Build type: native build
Project name: check
Project version: 0.14.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Has header "dlfcn.h" : YES 
Has header "errno.h" : YES 
Has header "fcntl.h" : YES 
Has header "inttypes.h" : YES 
Has header "limits.h" : YES 
Has header "locale.h" : YES 
Has header "memory.h" : YES 
Has header "regex.h" : YES 
Has header "signal.h" : YES 
Has header "stdarg.h" : YES 
Has header "stddef.h" : YES 
Has header "stdint.h" : YES 
Has header "stdlib.h" : YES 
Has header "strings.h" : YES 
Has header "string.h" : YES 
Has header "sys/stat.h" : YES 
Has header "sys/time.h" : YES 
Has header "sys/types.h" : YES 
Has header "sys/wait.h" : YES 
Has header "time.h" : YES 
Has header "unistd.h" : YES 
Has header "varargs.h" : YES 
Checking for function "clock_gettime" : YES 
Checking for function "alarm" : YES 
Checking for function "localtime_r" : YES 
Checking for function "setenv" : YES 
Checking for function "strdup" : YES 
Checking for function "strsignal" : NO 
Checking for function "fork" : YES 
Checking for function "getline" : YES 
Checking for function "getpid" : YES 
Checking for function "gettimeofday" : YES 
Checking for function "malloc" : YES 
Checking for function "mkstemp" : YES 
Checking for function "realloc" : YES 
Checking for function "regcomp" : YES 
Checking for function "regexec" : YES 
Checking for function "sigaction" : YES 
Checking for function "snprintf" : YES 
Checking for function "vasprintf" : NO 
Checking for function "va-copy" : NO 
Checking for function "vsnprintf" : YES 
Checking for size of "char" : 1
Checking for size of "int" : 4
Checking for size of "long" : 8
Checking for size of "short" : 2
Checking for size of "void*" : 8
Checking for size of "short" : 2
Checking for size of "int" : 4
Checking for size of "long" : 8
Checking for size of "long long" : 8
Checking for size of "unsigned short" : 2
Checking for size of "unsigned" : 4
Checking for size of "unsigned long" : 8
Checking for size of "unsigned long long" : 8
Checking for size of "__int64" : -1
Checking for size of "unsigned __int64" : -1
Checking for size of "int16_t" : 2
Checking for size of "int32_t" : 4
Checking for size of "int64_t" : 8
Checking for size of "intmax_t" : 8
Checking for size of "uint8_t" : 1
Checking for size of "uint16_t" : 2
Checking for size of "uint32_t" : 4
Checking for size of "uint64_t" : 8
Checking for size of "uintmax_t" : 8
Checking for type "clock_t" : YES 
Checking for size of "clock_t" : 8
Checking for type "clockid_t" : YES 
Checking for size of "clock_t" : 8
Checking for type "size_t" : YES 
Checking for size of "size_t" : 8
Checking for type "ssize_t" : YES 
Checking for size of "ssize_t" : 8
Checking for type "pid_t" : YES 
Checking for size of "pid_t" : 4
Checking for type "timer_t" : YES 
Checking for size of "timer_t" : 8
Checking for type "int16_t" : YES 
Checking for type "int32_t" : YES 
Checking for type "int64_t" : YES 
Checking for type "intmax_t" : YES 
Checking for type "uint8_t" : YES 
Checking for type "uint16_t" : YES 
Checking for type "uint32_t" : YES 
Checking for type "uint64_t" : YES 
Checking for type "uintmax_t" : YES 
Header <stdint.h> has symbol "INT64_MAX" : YES 
Header <stdint.h> has symbol "INT64_MIN" : YES 
Header <stdint.h> has symbol "UINT32_MAX" : YES 
Header <stdint.h> has symbol "UINT64_MAX" : YES 
Header <stdint.h> has symbol "SIZE_MAX" : YES 
Header <stdint.h> has symbol "SSIZE_MAX" : NO 
Header <limits.h> has symbol "SSIZE_MAX" : YES 
Library m found: YES
Header <math.h> has symbol "floor" : YES 
Library rt found: YES
Header <time.h> has symbol "clock_gettime" : YES 
Library subunit found: NO
Configuring config.h using configuration
Message: Adding strsignal.c to compat sources
Configuring check.h using configuration
Configuring check_stdint.h using configuration
Build targets in project: 6

Found ninja-1.10.0 at /usr/bin/ninja
meson setup: ☑
ninja: Entering directory `/tmp/tmpmwdxrkof/bin'
[3/47] Compiling C object 'src/25a6634@@check@sta/check.c.o'
FAILED: src/25a6634@@check@sta/check.c.o 
cc -Isrc/25a6634@@check@sta -Isrc -I../src/check-0.14.0/src -Iinternal -I../src/check-0.14.0/internal -Ilib -I../src/check-0.14.0/lib -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -g -DHAVE_SNPRINTF=1 -DHAVE_VSNPRINTF=1 -DHAVE_FORK=1 -DHAVE_MKSTEMP=1 -DHAVE_DECL_ALARM=1 -DHAVE_REGEX=1 -DENABLE_REGEX=1 -DHAVE_LIBRT=1 -DENABLE_SUBUNIT=0 -fPIC -DHAVE_CONFIG_H=1 '' -MD -MQ 'src/25a6634@@check@sta/check.c.o' -MF 'src/25a6634@@check@sta/check.c.o.d' -o 'src/25a6634@@check@sta/check.c.o' -c ../src/check-0.14.0/src/check.c
cc: error: : No such file or directory
[4/47] Compiling C object 'lib/76b5a35@@compat@sta/strsignal.c.o'
ninja: build stopped: subcommand failed.
ninja test: ☒
```

Could you please take a look? The tool I use to check this can be found here: https://github.com/mesonbuild/mesonwrap

**Comment by JPTIZ** [comment]
> Hi, there are 2 issues with the PR:
> 
> 1. It would be nice to put a `LICENSE.build`, you can take a look on the master branch or make your own. This is the license that covers build files you contribute. Jussi's code is licensed under MIT so if you would like to reuse MIT it's perfectly fine. You can just use the file from the master branch verbatim.

OH sorry, it "clicked in my head" now what you meant by that, hadn't checked the update in master before. I'm gonna rebase to add the file.

> 
> 2. The code doesn't build. The log is below.
> 
> 
> ```
> $ mesonwrap review check --pull-request=3 --allow-no-license --allow-other-files
> Inspecting project check, branch 0.14.0.
> ...
> cc: error: : No such file or directory
> [4/47] Compiling C object 'lib/76b5a35@@compat@sta/strsignal.c.o'
> ninja: build stopped: subcommand failed.
> ninja test: ☒
> ```
> 
> Could you please take a look? The tool I use to check this can be found here: https://github.com/mesonbuild/mesonwrap

Okay, that's strange, it doesn't find a file, but which one?...hm... It works on my machine (TM) - but haven't tested with the tool. Lemme use it to reproduce (and fix) the error here.

**Comment by legeana** [comment]
The tool basically tries to merge the code and the patch how it would be done by the meson client itself. Problems with this usually indicate that something is not aligned properly in the patch/source tree merging. The tool has `--export-sources` flag to export how the source tree, you might be able to use it to see how the merged version looks.

**Comment by JPTIZ** [comment]
Okay, I managed to check here in Windows and here it works with `cl` but not with `gcc`, but somehow in Linux it doesn't even run `mesonwrap` (it returns `401: Bad Credentials`).

**Comment by legeana** [comment]
I am not sure why this happens. You don't have github token in the config (obviously) but that should not be an issue as GitHub falls back on a freebie ACL.

You can create a `~/.config/mesonwrap.ini` with the following contents
```
[mesonwrap]
github_token = <secret>
```
and try again, see https://github.com/settings/tokens. You need repo rights for this to work.

To make your life easier the exported source tree looks like this:

```
/tmp/sources/
└── check-0.14.0
    ├── appveyor.yml
    ├── AUTHORS
    ├── ChangeLog
    ├── check.m4
    ├── checkmk
    │   ├── checkmk.in
    │   ├── CMakeLists.txt
    │   ├── doc
    │   │   ├── checkmk.1
    │   │   ├── checkmk.sgml
    │   │   ├── manpage.links
    │   │   └── manpage.refs
    │   ├── examples
    │   │   ├── basic_complete.ts
    │   │   └── multiple_everything.ts
    │   ├── Makefile.am
    │   ├── README
    │   └── test
    │       ├── argument_ws
    │       │   ├── in
    │       │   └── x_output
    │       ├── basic_complete
    │       │   ├── in
    │       │   └── x_output
    │       ├── between_the_lines
    │       │   ├── in
    │       │   └── x_output
    │       ├── case_insensitive_pp
    │       │   ├── in
    │       │   └── x_output
    │       ├── check_checkmk
    │       ├── clean_mode
    │       │   ├── cmd
    │       │   ├── in
    │       │   └── x_output
    │       ├── declarations
    │       │   ├── in
    │       │   └── x_output
    │       ├── empty_input
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── invalid_ucn
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── main_post
    │       │   ├── in
    │       │   └── x_output
    │       ├── main_post_multiple
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── main_pre_after_post
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── main_pre_multiple
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── multiple_everything
    │       │   ├── in
    │       │   └── x_output
    │       ├── name_enc
    │       │   ├── cmd
    │       │   └── x_output
    │       ├── no_args
    │       │   ├── cmd
    │       │   ├── in
    │       │   └── x_output
    │       ├── non_word_chars
    │       │   ├── in
    │       │   └── x_output
    │       ├── not_really_repeated
    │       │   ├── in
    │       │   └── x_output
    │       ├── num_start_test_name
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── pass_thru
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── repeated_argument_tests
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── repeated_suites
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── repeated_tcases
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── repeated_tests
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── single_test_line
    │       │   ├── in
    │       │   └── x_output
    │       ├── tcase_implied_repeat
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── test_after_main_post
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── test_after_main_pre
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── test_chars
    │       │   ├── in
    │       │   ├── x_err
    │       │   └── x_output
    │       ├── trailing_ws
    │       │   ├── in
    │       │   └── x_output
    │       └── ucn
    │           ├── in
    │           └── x_output
    ├── check.pc.in
    ├── cmake
    │   ├── BuildType.cmake
    │   ├── check-config.cmake.in
    │   ├── CheckHeaderDirent.cmake
    │   ├── check_stdint.h.in
    │   ├── CheckStructMember.cmake
    │   ├── CheckTypeExists.cmake
    │   └── config.h.in
    ├── CMakeLists.txt
    ├── configure.ac
    ├── contrib
    │   ├── check_unittest.txt
    │   ├── eclipse
    │   │   ├── check_template_eclipse_helios.xml
    │   │   └── README
    │   ├── improved_make_check
    │   │   ├── check.mk
    │   │   ├── COPYING
    │   │   └── README
    │   ├── make_macros
    │   └── XML_for_JUnit.xsl
    ├── COPYING.LESSER
    ├── doc
    │   ├── check.texi
    │   ├── doxygen.conf
    │   ├── doxygen-devel.conf
    │   ├── example
    │   │   ├── cmake
    │   │   │   ├── config.h.in
    │   │   │   ├── COPYING-CMAKE-SCRIPTS.txt
    │   │   │   └── FindCheck.cmake
    │   │   ├── CMakeLists.txt
    │   │   ├── configure.ac
    │   │   ├── Makefile.am
    │   │   ├── README
    │   │   ├── src
    │   │   │   ├── CMakeLists.txt
    │   │   │   ├── main.c
    │   │   │   ├── Makefile.am
    │   │   │   ├── money.1.c
    │   │   │   ├── money.1.h
    │   │   │   ├── money.2.h
    │   │   │   ├── money.3.c
    │   │   │   ├── money.4.c
    │   │   │   ├── money.5.c
    │   │   │   ├── money.6.c
    │   │   │   ├── money.c
    │   │   │   └── money.h
    │   │   └── tests
    │   │       ├── check_money.1.c
    │   │       ├── check_money.2.c
    │   │       ├── check_money.3.c
    │   │       ├── check_money.6.c
    │   │       ├── check_money.7.c
    │   │       ├── check_money.c
    │   │       ├── CMakeLists.txt
    │   │       └── Makefile.am
    │   ├── fdl.texi
    │   └── Makefile.am
    ├── HACKING
    ├── index.html
    ├── internal
    │   ├── config.h.meson
    │   └── meson.build
    ├── lib
    │   ├── alarm.c
    │   ├── clock_gettime.c
    │   ├── CMakeLists.txt
    │   ├── fpclassify.c
    │   ├── getline.c
    │   ├── gettimeofday.c
    │   ├── libcompat.c
    │   ├── libcompat.h
    │   ├── localtime_r.c
    │   ├── Makefile.am
    │   ├── malloc.c
    │   ├── meson.build
    │   ├── realloc.c
    │   ├── snprintf.c
    │   ├── strdup.c
    │   ├── strsignal.c
    │   ├── timer_create.c
    │   ├── timer_delete.c
    │   └── timer_settime.c
    ├── LICENSE.build
    ├── m4
    │   ├── acx_pthread.html
    │   ├── acx_pthread.m4
    │   ├── ax_c_check_flag.html
    │   ├── ax_c_check_flag.m4
    │   ├── ax_cflags_warn_all_ansi.html
    │   ├── ax_cflags_warn_all_ansi.m4
    │   ├── ax_create_stdint_h.m4
    │   ├── librt_timers.m4
    │   └── snprintf.m4
    ├── Makefile.am
    ├── meson.build
    ├── meson_options.txt
    ├── NEWS
    ├── README.md
    ├── src
    │   ├── check.c
    │   ├── check_error.c
    │   ├── check_error.h
    │   ├── check.h.in
    │   ├── check_impl.h
    │   ├── check_list.c
    │   ├── check_list.h
    │   ├── check_log.c
    │   ├── check_log.h
    │   ├── check_msg.c
    │   ├── check_msg.h
    │   ├── check_pack.c
    │   ├── check_pack.h
    │   ├── check_print.c
    │   ├── check_print.h
    │   ├── check_run.c
    │   ├── check_str.c
    │   ├── check_str.h
    │   ├── CMakeLists.txt
    │   ├── Makefile.am
    │   └── meson.build
    ├── tests
    │   ├── check_check_exit.c
    │   ├── check_check_export_main.c
    │   ├── check_check_fixture.c
    │   ├── check_check_fork.c
    │   ├── check_check.h
    │   ├── check_check_limit.c
    │   ├── check_check_log.c
    │   ├── check_check_log_internal.c
    │   ├── check_check_main.c
    │   ├── check_check_master.c
    │   ├── check_check_msg.c
    │   ├── check_check_pack.c
    │   ├── check_check_selective.c
    │   ├── check_check_sub.c
    │   ├── check_check_tags.c
    │   ├── check_list.c
    │   ├── check_mem_leaks.c
    │   ├── check_nofork.c
    │   ├── check_nofork_teardown.c
    │   ├── check_set_max_msg_size.c
    │   ├── check_stress.c
    │   ├── check_thread_stress.c
    │   ├── CMakeLists.txt
    │   ├── cmake_project_usage_test
    │   │   ├── CMakeLists.txt
    │   │   ├── README
    │   │   └── src
    │   │       ├── CMakeLists.txt
    │   │       ├── tests.c
    │   │       ├── test_suite.c
    │   │       └── test_suite.h
    │   ├── ex_output.c
    │   ├── Makefile.am
    │   ├── meson.build
    │   ├── test_check_nofork.sh
    │   ├── test_check_nofork_teardown.sh
    │   ├── test_log_output.sh
    │   ├── test_mem_leaks.sh
    │   ├── test_output.sh
    │   ├── test_output_strings
    │   ├── test_set_max_msg_size.sh
    │   ├── test_tap_output.sh
    │   ├── test_vars.in
    │   └── test_xml_output.sh
    ├── THANKS
    ├── TODO
    ├── travis.sh
    ├── web
    │   ├── css
    │   │   └── style.css
    │   ├── img
    │   │   ├── header_bg.gif
    │   │   ├── menu_bg.gif
    │   │   ├── side_bg.gif
    │   │   └── tab_bg.gif
    │   ├── install.html
    │   ├── License.txt
    │   └── users-of-check.html
    └── xml
        └── check_unittest.xslt
```

The layout looks reasonable to me.

```
$ ninja -C builddir src/25a6634@@check@sta/check.c.o
ninja: Entering directory `builddir'
[1/1] Compiling C object 'src/25a6634@@check@sta/check.c.o'
FAILED: src/25a6634@@check@sta/check.c.o 
cc -Isrc/25a6634@@check@sta -Isrc -I../src -Iinternal -I../internal -Ilib -I../lib -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -g -DHAVE_SNPRINTF=1 -DHAVE_VSNPRINTF=1 -DHAVE_FORK=1 -DHAVE_MKSTEMP=1 -DHAVE_DECL_ALARM=1 -DHAVE_REGEX=1 -DENABLE_REGEX=1 -DHAVE_LIBRT=1 -DENABLE_SUBUNIT=0 -fPIC -DHAVE_CONFIG_H=1 '' -MD -MQ 'src/25a6634@@check@sta/check.c.o' -MF 'src/25a6634@@check@sta/check.c.o.d' -o 'src/25a6634@@check@sta/check.c.o' -c ../src/check.c
cc: error: : No such file or directory
ninja: build stopped: subcommand failed.
```

The confusing thing is this seems to be GCC-related.

```
$ env CC=clang CXX=clang++ meson clangdir
$ ninja -C clangdir/
ninja: Entering directory `clangdir/'
[46/46] Linking target tests/check_mem_leaks
```

**Comment by JPTIZ** [comment]
Wow, that was really attentious of you! Thanks :D

But wow, yeah, seems something strange about gcc, specially because it says an _unnamed_ file hasn't been found.

(Also, for the token, which accesses should I grant to it when creating? Just check the Repos permissions like this?)
image


EDIT: __wow__ I just realized that `''` in the middle of the compilation line. GCC is thinking that's an input file. Probably something related to how I send args.

**Comment by legeana** [comment]
To be honest I don't think I actually tested what permissions are required specifically. I know that repo is enough. The tool needs access to the repository and pull request public info in a read-only mode, so I don't think all of the repo permissions are necessary.

**Pull request merged**
